### ISSUE TITLE
Request for the calculation and definition of inputs in ASU and MSU

### ISSUE THREAD

**Issue by SteamerLee** [CMACH508/2021-WangZhicheng#7]
Hi, 
First of all, thanks for sharing this interesting work on portfolio opt. I would try to reproduce the DeepTrader framework based on the provided codes, and would like to know the definition and calculation of every input feature in ASU and MSU modules so that I can create our own dataset tested on the codes. I have checked other issuses where several inpurt features like max./min. vol., are mentioned, but I did't find their definitions/calculation. Could you please provide some hints about them? 

Many thanks!

**Comment by CMACH508** [comment]
The dataset for stocks has six dimensions: close, max, min, volume, MC, PE. The dataset for markets can have only market index. They are then processed in the DataGenerator class in envrionment and entered into ASU and MSU respectively.

**Comment by SteamerLee** [comment]
THANKS for the prompt reply!!
